'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

export type Language = 'English' | 'मराठी' | 'हिंदी'

export const labels = {
  English: {
    // =========================
    // COMMON
    // =========================
    dashboard: 'Dashboard',
    home: 'Home',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    continue: 'Continue',
    submit: 'Submit',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    search: 'Search',
    filter: 'Filter',
    reset: 'Reset',
    refresh: 'Refresh',
    loading: 'Loading...',
    retry: 'Retry',
    viewDetails: 'View details →',
    optional: 'Optional',
    required: 'Required',
    available: 'Available',
    total: 'Total',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    name: 'Name',
    phone: 'Phone number',
    email: 'Email',
    language: 'Language',
    price: 'Price',
    quantity: 'Quantity',
    location: 'Location',
    crop: 'Crop',
    farmer: 'Farmer',
    buyer: 'Buyer',
    company: 'Company',
    market: 'Market',
    markets: 'Markets',
    offer: 'Offer',
    offers: 'Buyer Offers',
    accepted: 'Accepted',
    rejected: 'Rejected',
    pending: 'Pending',
    completed: 'Completed',

    // =========================
    // ROLE SELECTION
    // =========================
    chooseRole: 'Choose your role',
    selectRole: 'Select how you want to use KrishiSetu',
    iAmFarmer: 'I am a Farmer',
    iAmBuyer: 'I am a Buyer',
    farmerDescription: 'Sell your produce at the best possible net return.',
    buyerDescription: 'Find quality produce and connect directly with farmers.',
    farmerRole: 'Farmer',
    buyerRole: 'Buyer',

    // =========================
    // LOGIN / REGISTRATION
    // =========================
    login: 'Login',
    register: 'Register',
    farmerLogin: 'Farmer Login',
    buyerLogin: 'Buyer Login',
    farmerRegistration: 'Farmer Registration',
    buyerRegistration: 'Buyer Registration',
    enterDetails: 'Enter your details to continue.',
    enterFarmerDetails: 'Enter your details to continue as a farmer.',
    enterBuyerDetails: 'Enter your details to continue as a buyer.',
    farmerName: 'Farmer name',
    businessName: 'Business / Organization name',
    companyName: 'Company name',
    mobileNumber: 'Mobile number',
    enterMobileNumber: 'Enter mobile number',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    enterOtp: 'Enter OTP',
    otpSent: 'OTP sent successfully.',
    invalidOtp: 'Invalid OTP. Please try again.',
    loginSuccessful: 'Login successful.',
    registrationSuccessful: 'Registration successful.',
    uploadId: 'Upload Digital Farmer ID',
    digitalFarmerId: 'Digital Farmer ID (Kisan Pehchan Patra)',
    chooseFile: 'Choose file',
    noFileChosen: 'No file chosen',
    idUploadOptional: 'Digital Farmer ID upload is optional.',
    qualityCertificate: 'Quality certificate',
    qualityCertificateOptional: 'Quality certificate is optional.',
    profileCreated: 'Profile created successfully.',

    // =========================
    // FARMER DASHBOARD
    // =========================
    farmerDashboard: 'Farmer Dashboard',
    farmerDashboardSubtitle: 'Find the best market for your produce.',
    whatsYourName: "What's your name?",
    enterYourName: 'Enter your name',
    welcomeFarmer: 'Welcome, Farmer',
    yourProduce: 'Your Produce',
    addProduce: 'Add Produce',
    addProduceListing: 'Add Produce Listing',
    cropDetails: 'Crop details',
    selectCrop: 'Select crop',
    enterQuantity: 'Enter quantity',
    quantityUnit: 'Quantity (quintals)',
    expectedPrice: 'Expected price',
    expectedPricePerQuintal: 'Expected price (₹/quintal)',
    selectLocation: 'Select location',
    useMyLocation: 'Use my location',
    findBestMarket: 'Find best market',
    compareMarkets: 'Compare Markets',
    whereShouldYouSell: 'Where should you sell?',
    bestMarket: 'Best market',
    recommendedMarket: 'Recommended Market',
    bestEstimatedReturn: 'Best Estimated Return',
    todaysPrice: "Today's Price",
    currentPrice: 'Current Price',
    marketPrice: 'Market Price',
    governmentMsp: 'Government MSP',
    mspBenchmark: 'MSP Benchmark',
    aboveMsp: 'Above MSP',
    belowMsp: 'Below MSP',
    mspNotApplicable: 'MSP not applicable',
    priceDifference: 'Difference from MSP',
    netReturn: 'Net Return',
    estimatedNetReturn: 'Estimated Net Return',
    expectedNetReturn: 'Expected net return',
    estimatedTransport: 'Estimated transport',
    transportCost: 'Transport cost',
    handlingCost: 'Handling cost',
    otherCosts: 'Other costs',
    grossRevenue: 'Gross revenue',
    decision: 'Decision',
    sellingDecision: 'Selling Decision',
    sellNow: 'Sell Now',
    wait: 'Wait',
    sellAt: 'Sell at',
    highestReturnNote: 'Highest estimated net return after transport cost.',
    whyLabel: 'Why?',
    demoEstimate: 'Demo estimate',
    sampleData: 'Sample data',
    sampleDataFooter:
      'Sample / Historical Data · All values are estimates for prototype demonstration.',

    // =========================
    // MARKET COMPARISON
    // =========================
    comparisonTag: 'Market comparison',
    comparisonTitlePrefix: 'Where should you sell your',
    comparisonSubtitlePrefix:
      'Sorted by highest estimated net return for',
    comparisonSubtitleSuffix: 'quintals.',
    backToDashboard: '← Back to dashboard',
    bestNetReturn: 'Best net return',
    kmAway: 'km away',
    demandSuffix: 'DEMAND',
    priceLabel: 'Price',
    transportLabel: 'Transport',
    handlingLabel: 'Handling',
    netReturnLabel: 'Net return',
    marketComparison: 'Market comparison',
    compareMarketPrices: 'Compare market prices',
    estimatedRevenue: 'Estimated revenue',
    estimatedProfit: 'Estimated profit',
    marketDistance: 'Market distance',
    demand: 'Demand',
    highDemand: 'High demand',
    mediumDemand: 'Medium demand',
    lowDemand: 'Low demand',

    // =========================
    // FORECAST
    // =========================
    forecast: 'Forecast',
    priceForecast: 'Price Forecast',
    marketForecastEngine: 'Market Forecast and Design Engine',
    marketForecastAndDesignEngine: 'Market Forecast and Design Engine',
    priceTrends: 'Price Trends',
    trends: 'Price Trends',
    historicalPrices: 'Historical Prices',
    expectedPriceLabel: 'Expected price',
    predictedPrice: 'Predicted price',
    forecastPeriod: 'Forecast period',
    nextDays: 'Next few days',
    priceMovement: 'Price movement',
    rising: 'Rising',
    falling: 'Falling',
    stable: 'Stable',
    trend: 'Trend',
    forecastDisclaimer:
      'Forecast values are estimates based on available market data.',

    // =========================
    // MARKETPLACE
    // =========================
    marketplace: 'Marketplace',
    buyerMarketplaceTag: 'Buyer marketplace',
    buyerMarketplace: 'Buyer Marketplace',
    findBuyers: 'Find sellers',
    findBuyersSubtitle:
      'Connect your produce with buyers offering competitive prices.',
    findMoreBuyers: 'Find more buyers',
    myOffers: 'My Offers',
    farmerOffers: 'Farmer Offers',
    buyerOffers: 'Buyer Offers',
    buyerOffersTitle: 'Buyer offers',
    buyerOffersSubtitle:
      'Review every detail and make the final decision.',
    farmerDecisionsTag: 'Farmer decisions',
    currentContextTitle: 'Your current selling context',
    offerComparisonTitle: 'Offer comparison',
    currentMandiPrice: 'Current mandi price',
    availableQuantity: 'Available quantity',
    offeredPrice: 'Offered price',
    offerPrice: 'Offer price',
    makeOffer: 'Make an Offer',
    makeAnOffer: 'Make an Offer',
    submitOffer: 'Submit Offer',
    offerSubmitted: 'Offer submitted successfully.',
    offerSubmittedTitle: 'Offer Submitted',
    pendingFarmerResponse: 'Pending Farmer Response',
    offerAcceptedTitle: 'Offer Accepted',
    offerRejected: 'Offer rejected',
    offerRejectedMessage: 'This offer was rejected.',
    offerMessage: 'Message',
    optionalMessage: 'Message (optional)',
    buyerCompany: 'Buyer company',
    loggedInBuyer: 'Logged-in buyer',
    buyerIdentity: 'Buyer identity',
    offerBelongsToCompany: 'This offer will be placed on behalf of your registered company.',
    noOffers: 'No offers available.',
    noListings: 'No listings found.',
    listing: 'Listing',
    listings: 'Listings',
    createListing: 'Create listing',
    produceListing: 'Produce listing',
    farmerListing: 'Farmer listing',
    seller: 'Seller',
    buyerDetails: 'Buyer details',
    farmerDetails: 'Farmer details',

    // =========================
    // MARKETPLACE FILTERS
    // =========================
    filterCrop: 'Crop',
    filterLocation: 'Location',
    filterGrade: 'Quality grade',
    minPrice: 'Minimum price',
    maxPrice: 'Maximum price',
    qualityFilter: 'Quality',
    allQuality: 'All quality levels',
    gradeA: 'Grade A',
    gradeB: 'Grade B',
    gradeC: 'Grade C',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    sortBy: 'Sort by',
    highestPrice: 'Highest price',
    lowestPrice: 'Lowest price',
    nearestMarket: 'Nearest market',
    bestNetReturnSort: 'Best net return',

    // =========================
    // QUALITY
    // =========================
    quality: 'Quality',
    qualityGrade: 'Quality Grade',
    addQuality: 'Add quality',
    selectQuality: 'Select quality grade',
    farmerDeclaredQuality: 'Farmer-declared quality',
    buyerVerifiedQuality: 'Buyer-verified quality',
    qualityInspection: 'Quality inspection',
    qualityDescription: 'Quality description',
    qualityNotes: 'Quality notes',
    gradeThisProduce: 'Grade this produce',
    gradingTag: 'Quality grading',
    assignGrade: 'Assign quality grade',
    gradeALabel: 'Grade A · Premium',
    gradeANote: 'Minimal defects, uniform size/color.',
    gradeBLabel: 'Grade B · Standard',
    gradeBNote: 'Minor defects, market-acceptable.',
    gradeCLabel: 'Grade C · Below standard',
    gradeCNote: 'Visible defects or damage.',
    finalPriceLabel: 'Final price after grading (₹/quintal)',
    totalAtPricePrefix: 'Total at this price:',
    finalizeGradingBtn: 'Finalize Grading & Price',
    gradeSetPriceBtn: 'Grade & Set Final Price',
    gradedByBuyerNote:
      'Graded and priced by the buyer. Next step: arrange transport for the accepted quantity.',
    offerAcceptedGradeNote:
      'Buyer connection established in prototype. Next step: buyer grades quality and sets the final price.',
    planTransportBtn: 'Plan Transport for This Offer',

    // =========================
    // FARMER RATING
    // =========================
    rating: 'Rating',
    ratings: 'Ratings',
    farmerRating: 'Farmer rating',
    rateFarmer: 'Rate this farmer',
    rateYourExperience: 'Rate your experience',
    starRating: 'Star rating',
    review: 'Review',
    writeReview: 'Write a review',
    submitRating: 'Submit Rating',
    ratingSubmitted: 'Rating submitted successfully.',
    ratingEligibility:
      'You can rate a farmer only after completing a purchase from them.',
    notEligibleToRate: 'You are not eligible to rate this farmer yet.',
    completedTransactionRequired:
      'A completed transaction is required to submit a rating.',

    // =========================
    // LOGISTICS
    // =========================
    logistics: 'Logistics',
    logisticsTag: 'Logistics',
    moveProduce: 'Move your produce',
    transport: 'Transport',
    transportOptionsTag: 'Transport options',
    chooseTransport: 'Choose how to transport',
    transportVehicle: 'Transport vehicle',
    truck: 'Truck',
    miniTruck: 'Mini truck',
    pickupTruck: 'Pickup truck',
    estimatedCost: 'Estimated cost',
    distance: 'Distance',
    pickup: 'Pickup',
    delivery: 'Delivery',
    pickupAddress: 'Pickup address',
    deliveryAddress: 'Delivery address',
    schedulePickupTitle: 'Schedule pickup',
    pickupDateLabel: 'Pickup date',
    pickupTimeLabel: 'Pickup time',
    schedulePickupBtn: 'Schedule Pickup',
    confirmTransport: 'Confirm transport',
    transportScheduled: 'Transport scheduled successfully.',
    transportEstimate: 'Transport estimate',
    transportAvailable: 'Transport available',
    noTransportAvailable: 'No transport option available.',
    transportRate: 'Transport rate',
    costPerKm: 'Cost per km',

    // =========================
    // FRUITS & CROPS
    // =========================
    fruits: 'Fruits',
    vegetables: 'Vegetables',
    grains: 'Grains',
    pulses: 'Pulses',
    spices: 'Spices',
    selectCategory: 'Select category',
    mango: 'Mango',
    banana: 'Banana',
    apple: 'Apple',
    orange: 'Orange',
    grapes: 'Grapes',
    pomegranate: 'Pomegranate',
    guava: 'Guava',
    papaya: 'Papaya',
    watermelon: 'Watermelon',
    onion: 'Onion',
    potato: 'Potato',
    tomato: 'Tomato',
    cabbage: 'Cabbage',
    cauliflower: 'Cauliflower',
    brinjal: 'Brinjal',

    // =========================
    // MSP
    // =========================
    msp: 'MSP',
    mspFull: 'Minimum Support Price',
    mspBenchmarkTitle: 'Government MSP Benchmark',
    marketVsMsp: 'Market Price vs MSP',
    mspDifference: 'MSP difference',
    marketAboveMsp: 'Market price is above MSP.',
    marketBelowMsp: 'Market price is below MSP benchmark.',
    mspNotAvailable: 'MSP data not available for this commodity.',
    mspSource: 'MSP source',
    mspYear: 'MSP year',
    mspSeason: 'Marketing season',
    checkProcurementOptions:
      'Check available procurement options before selling.',

    // =========================
    // DECISION ENGINE
    // =========================
    recommendation: 'Recommendation',
    recommendationTag: 'KrishiSetu recommendation',
    sellingRecommendation: 'Selling recommendation',
    recommendedAction: 'Recommended action',
    highestReturn: 'Highest return',
    betterOption: 'Better option',
    decisionEngine: 'Decision Engine',
    netRealization: 'Net Realization',
    netRealizationEngine: 'Net Realization Engine',
    grossValue: 'Gross value',
    totalCosts: 'Total costs',
    spoilageRisk: 'Spoilage risk',
    lowSpoilageRisk: 'Low spoilage risk',
    mediumSpoilageRisk: 'Medium spoilage risk',
    highSpoilageRisk: 'High spoilage risk',
    demandScore: 'Demand score',
    priceTrendScore: 'Price trend score',
    transportScore: 'Transport score',

    // =========================
    // OFFLINE
    // =========================
    offline: 'Offline',
    online: 'Online',
    cached: 'Cached Data',
    offlineMode: 'Offline mode',
    offlineAvailable: 'Available offline',
    lastUpdated: 'Last updated',
    syncData: 'Sync data',
    syncing: 'Syncing...',
    syncComplete: 'Data synced successfully.',

    // =========================
    // PAGE HEADER
    // =========================
    startDemo: 'Start SIH Demo',
    backToComparison: '← Back to comparison',
    accessKrishiSetu: 'Access KrishiSetu',
    krishiSetu: 'KrishiSetu',

    // =========================
    // IMPACT
    // =========================
    impactBannerTag: 'Illustrative impact (sample cohort)',
    impactBannerBadge: 'Demo numbers — not measured yet',
    impactFarmersHelped: 'Farmers helped (demo cohort)',
    impactReturnLift: 'Avg. net return lift vs. nearest mandi',
    impactMarketsCompared: 'Markets compared per decision',

    // =========================
    // GRADING / TRANSACTION
    // =========================
    transaction: 'Transaction',
    transactionDetails: 'Transaction details',
    acceptedQuantity: 'Accepted quantity',
    finalPrice: 'Final price',
    totalAmount: 'Total amount',
    transactionCompleted: 'Transaction completed',
    transactionPending: 'Transaction pending',
    purchaseCompleted: 'Purchase completed',
    purchaseHistory: 'Purchase history',

    // =========================
    // ERRORS / VALIDATION
    // =========================
    somethingWentWrong: 'Something went wrong.',
    pleaseTryAgain: 'Please try again.',
    requiredField: 'This field is required.',
    enterValidQuantity: 'Please enter a valid quantity.',
    enterValidPrice: 'Please enter a valid price.',
    selectCropError: 'Please select a crop.',
    selectLocationError: 'Please select a location.',
    selectQualityError: 'Please select a quality grade.',
    loginRequired: 'Please login to continue.',
    buyerOnly: 'This action is available only to buyers.',
    farmerOnly: 'This action is available only to farmers.',
    transactionRequired: 'A completed transaction is required.',
    apiError: 'Unable to fetch live market data.',
    noMarketData: 'No market data available.',
    noForecastData: 'No forecast data available.',

    // =========================
    // FOOTER / INFO
    // =========================
    aboutKrishiSetu: 'About KrishiSetu',
    howItWorks: 'How it works',
    privacy: 'Privacy',
    terms: 'Terms',
    help: 'Help',
    support: 'Support',
    prototype: 'Prototype',
    demo: 'Demo',
    sample: 'Sample',
    allValuesEstimate:
      'All values shown are estimates for prototype demonstration.',

    // =========================
    // MARKET SUFFIX / COMMON PHRASES
    // =========================
    marketSuffix: 'Market',
    pricePerQuintal: '₹/quintal',
    perQuintal: 'per quintal',
    quintals: 'quintals',
    kg: 'kg',
    tonnes: 'tonnes',
    km: 'km',
    rupees: '₹',

    // =========================
    // DYNAMIC TEXT HELPERS
    // =========================
    todayCropPrice: "Today's {crop} Price",
    bestReturnForCrop: 'Best estimated return for {crop}',
    whereToSellCrop: 'Where should you sell your {crop}?',
    marketDistanceText: '{distance} km away',
    availableQuantityText: '{quantity} quintals available',
    offerPriceText: '₹{price}/quintal',
    totalAmountText: '₹{amount}',
    ratingText: '{rating}/5',
  },

  'मराठी': {
    // =========================
    // COMMON
    // =========================
    dashboard: 'डॅशबोर्ड',
    home: 'मुख्यपृष्ठ',
    back: 'मागे',
    next: 'पुढे',
    previous: 'मागील',
    continue: 'पुढे जा',
    submit: 'सबमिट करा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    close: 'बंद करा',
    confirm: 'पुष्टी करा',
    yes: 'होय',
    no: 'नाही',
    search: 'शोधा',
    filter: 'फिल्टर',
    reset: 'रीसेट',
    refresh: 'रिफ्रेश',
    loading: 'लोड होत आहे...',
    retry: 'पुन्हा प्रयत्न करा',
    viewDetails: 'तपशील पहा →',
    optional: 'ऐच्छिक',
    required: 'आवश्यक',
    available: 'उपलब्ध',
    total: 'एकूण',
    status: 'स्थिती',
    date: 'तारीख',
    time: 'वेळ',
    name: 'नाव',
    phone: 'फोन नंबर',
    email: 'ईमेल',
    language: 'भाषा',
    price: 'किंमत',
    quantity: 'प्रमाण',
    location: 'ठिकाण',
    crop: 'पीक',
    farmer: 'शेतकरी',
    buyer: 'खरेदीदार',
    company: 'कंपनी',
    market: 'बाजार',
    markets: 'बाजार',
    offer: 'ऑफर',
    offers: 'खरेदीदार ऑफर',
    accepted: 'स्वीकारले',
    rejected: 'नाकारले',
    pending: 'प्रलंबित',
    completed: 'पूर्ण',

    // ROLE
    chooseRole: 'तुमची भूमिका निवडा',
    selectRole: 'तुम्ही कृषीसेतूचा वापर कसा करू इच्छिता ते निवडा',
    iAmFarmer: 'मी शेतकरी आहे',
    iAmBuyer: 'मी खरेदीदार आहे',
    farmerDescription: 'तुमच्या मालासाठी सर्वोत्तम निव्वळ परतावा मिळवा.',
    buyerDescription: 'दर्जेदार माल शोधा आणि शेतकऱ्यांशी थेट संपर्क साधा.',
    farmerRole: 'शेतकरी',
    buyerRole: 'खरेदीदार',

    // LOGIN
    login: 'लॉगिन',
    register: 'नोंदणी',
    farmerLogin: 'शेतकरी लॉगिन',
    buyerLogin: 'खरेदीदार लॉगिन',
    farmerRegistration: 'शेतकरी नोंदणी',
    buyerRegistration: 'खरेदीदार नोंदणी',
    enterDetails: 'पुढे जाण्यासाठी तुमची माहिती भरा.',
    enterFarmerDetails: 'शेतकरी म्हणून पुढे जाण्यासाठी तुमची माहिती भरा.',
    enterBuyerDetails: 'खरेदीदार म्हणून पुढे जाण्यासाठी तुमची माहिती भरा.',
    farmerName: 'शेतकऱ्याचे नाव',
    businessName: 'व्यवसाय / संस्थेचे नाव',
    companyName: 'कंपनीचे नाव',
    mobileNumber: 'मोबाइल नंबर',
    enterMobileNumber: 'मोबाइल नंबर भरा',
    sendOtp: 'OTP पाठवा',
    verifyOtp: 'OTP तपासा',
    enterOtp: 'OTP भरा',
    otpSent: 'OTP यशस्वीरित्या पाठवला आहे.',
    invalidOtp: 'अवैध OTP. पुन्हा प्रयत्न करा.',
    loginSuccessful: 'लॉगिन यशस्वी झाले.',
    registrationSuccessful: 'नोंदणी यशस्वी झाली.',
    uploadId: 'डिजिटल शेतकरी ओळखपत्र अपलोड करा',
    digitalFarmerId: 'डिजिटल शेतकरी ओळखपत्र (किसान पहचान पत्र)',
    chooseFile: 'फाइल निवडा',
    noFileChosen: 'फाइल निवडलेली नाही',
    idUploadOptional: 'डिजिटल शेतकरी ओळखपत्र अपलोड करणे ऐच्छिक आहे.',
    qualityCertificate: 'गुणवत्ता प्रमाणपत्र',
    qualityCertificateOptional: 'गुणवत्ता प्रमाणपत्र ऐच्छिक आहे.',
    profileCreated: 'प्रोफाइल यशस्वीरित्या तयार झाले.',

    // FARMER
    farmerDashboard: 'शेतकरी डॅशबोर्ड',
    farmerDashboardSubtitle: 'तुमच्या मालासाठी सर्वोत्तम बाजार शोधा.',
    whatsYourName: 'तुमचे नाव काय आहे?',
    enterYourName: 'तुमचे नाव भरा',
    welcomeFarmer: 'स्वागत आहे, शेतकरी',
    yourProduce: 'तुमचा माल',
    addProduce: 'माल जोडा',
    addProduceListing: 'मालाची नोंदणी करा',
    cropDetails: 'पिकाची माहिती',
    selectCrop: 'पीक निवडा',
    enterQuantity: 'प्रमाण भरा',
    quantityUnit: 'प्रमाण (क्विंटल)',
    expectedPrice: 'अपेक्षित किंमत',
    expectedPricePerQuintal: 'अपेक्षित किंमत (₹/क्विंटल)',
    selectLocation: 'ठिकाण निवडा',
    useMyLocation: 'माझे ठिकाण वापरा',
    findBestMarket: 'सर्वोत्तम बाजार शोधा',
    compareMarkets: 'बाजारांची तुलना करा',
    whereShouldYouSell: 'तुमचा माल कुठे विकावा?',
    bestMarket: 'सर्वोत्तम बाजार',
    recommendedMarket: 'शिफारस केलेला बाजार',
    bestEstimatedReturn: 'सर्वोत्तम अंदाजित परतावा',
    todaysPrice: 'आजचा भाव',
    currentPrice: 'सध्याची किंमत',
    marketPrice: 'बाजारभाव',
    governmentMsp: 'सरकारी MSP',
    mspBenchmark: 'MSP तुलना',
    aboveMsp: 'MSP पेक्षा जास्त',
    belowMsp: 'MSP पेक्षा कमी',
    mspNotApplicable: 'MSP लागू नाही',
    priceDifference: 'MSP मधील फरक',
    netReturn: 'निव्वळ परतावा',
    estimatedNetReturn: 'अंदाजित निव्वळ परतावा',
    expectedNetReturn: 'अपेक्षित निव्वळ परतावा',
    estimatedTransport: 'अंदाजित वाहतूक',
    transportCost: 'वाहतूक खर्च',
    handlingCost: 'हाताळणी खर्च',
    otherCosts: 'इतर खर्च',
    grossRevenue: 'एकूण उत्पन्न',
    decision: 'निर्णय',
    sellingDecision: 'विक्रीचा निर्णय',
    sellNow: 'आता विका',
    wait: 'थांबा',
    sellAt: 'येथे विका',
    highestReturnNote: 'वाहतूक खर्चानंतर सर्वाधिक अंदाजित निव्वळ परतावा.',
    whyLabel: 'का?',
    demoEstimate: 'डेमो अंदाज',
    sampleData: 'नमुना डेटा',
    sampleDataFooter:
      'नमुना / ऐतिहासिक डेटा · सर्व मूल्ये प्रोटोटाइप प्रात्यक्षिकासाठी अंदाजित आहेत.',

    // COMPARISON
    comparisonTag: 'बाजार तुलना',
    comparisonTitlePrefix: 'तुमचा माल कुठे विकावा',
    comparisonSubtitlePrefix:
      'सर्वाधिक अंदाजित निव्वळ परताव्यानुसार क्रमवारी',
    comparisonSubtitleSuffix: 'क्विंटलसाठी.',
    backToDashboard: '← डॅशबोर्डकडे परत जा',
    bestNetReturn: 'सर्वोत्तम निव्वळ परतावा',
    kmAway: 'किमी अंतर',
    demandSuffix: 'मागणी',
    priceLabel: 'किंमत',
    transportLabel: 'वाहतूक',
    handlingLabel: 'हाताळणी',
    netReturnLabel: 'निव्वळ परतावा',
    marketComparison: 'बाजार तुलना',
    compareMarketPrices: 'बाजारभावांची तुलना करा',
    estimatedRevenue: 'अंदाजित उत्पन्न',
    estimatedProfit: 'अंदाजित नफा',
    marketDistance: 'बाजाराचे अंतर',
    demand: 'मागणी',
    highDemand: 'जास्त मागणी',
    mediumDemand: 'मध्यम मागणी',
    lowDemand: 'कमी मागणी',

    // FORECAST
    forecast: 'अंदाज',
    priceForecast: 'किंमत अंदाज',
    marketForecastEngine: 'बाजार अंदाज आणि निर्णय इंजिन',
    marketForecastAndDesignEngine: 'बाजार अंदाज आणि निर्णय इंजिन',
    priceTrends: 'किंमत कल',
    trends: 'किंमत कल',
    historicalPrices: 'ऐतिहासिक किंमती',
    expectedPriceLabel: 'अपेक्षित किंमत',
    predictedPrice: 'अंदाजित किंमत',
    forecastPeriod: 'अंदाज कालावधी',
    nextDays: 'पुढील काही दिवस',
    priceMovement: 'किंमतीतील बदल',
    rising: 'वाढत आहे',
    falling: 'कमी होत आहे',
    stable: 'स्थिर',
    trend: 'कल',
    forecastDisclaimer:
      'अंदाज उपलब्ध बाजार डेटावर आधारित आहेत.',

    // MARKETPLACE
    marketplace: 'बाजारपेठ',
    buyerMarketplaceTag: 'खरेदीदार बाजारपेठ',
    buyerMarketplace: 'खरेदीदार बाजारपेठ',
    findBuyers: 'खरेदीदार शोधा',
    findBuyersSubtitle:
      'स्पर्धात्मक किंमत देणाऱ्या खरेदीदारांशी तुमचा माल जोडा.',
    findMoreBuyers: 'अधिक खरेदीदार शोधा',
    myOffers: 'माझ्या ऑफर',
    farmerOffers: 'शेतकऱ्यांच्या ऑफर',
    buyerOffers: 'खरेदीदार ऑफर',
    buyerOffersTitle: 'खरेदीदार ऑफर',
    buyerOffersSubtitle: 'प्रत्येक तपशील तपासा आणि अंतिम निर्णय घ्या.',
    farmerDecisionsTag: 'शेतकरी निर्णय',
    currentContextTitle: 'तुमचा सध्याचा विक्री संदर्भ',
    offerComparisonTitle: 'ऑफर तुलना',
    currentMandiPrice: 'सध्याचा बाजारभाव',
    availableQuantity: 'उपलब्ध प्रमाण',
    offeredPrice: 'ऑफर केलेली किंमत',
    offerPrice: 'ऑफर किंमत',
    makeOffer: 'ऑफर द्या',
    makeAnOffer: 'ऑफर द्या',
    submitOffer: 'ऑफर सबमिट करा',
    offerSubmitted: 'ऑफर यशस्वीरित्या सबमिट झाली.',
    offerSubmittedTitle: 'ऑफर सबमिट झाली',
    pendingFarmerResponse: 'शेतकऱ्याच्या प्रतिसादाची प्रतीक्षा',
    offerAcceptedTitle: 'ऑफर स्वीकारली',
    offerRejected: 'ऑफर नाकारली',
    offerRejectedMessage: 'ही ऑफर नाकारण्यात आली.',
    offerMessage: 'संदेश',
    optionalMessage: 'संदेश (ऐच्छिक)',
    buyerCompany: 'खरेदीदार कंपनी',
    loggedInBuyer: 'लॉग-इन केलेला खरेदीदार',
    buyerIdentity: 'खरेदीदार ओळख',
    offerBelongsToCompany:
      'ही ऑफर तुमच्या नोंदणीकृत कंपनीच्या वतीने केली जाईल.',
    noOffers: 'कोणत्याही ऑफर उपलब्ध नाहीत.',
    noListings: 'कोणत्याही नोंदी सापडल्या नाहीत.',
    listing: 'नोंद',
    listings: 'नोंदी',
    createListing: 'नोंद तयार करा',
    produceListing: 'मालाची नोंद',
    farmerListing: 'शेतकऱ्याची नोंद',
    seller: 'विक्रेता',
    buyerDetails: 'खरेदीदाराची माहिती',
    farmerDetails: 'शेतकऱ्याची माहिती',

    // FILTERS
    filterCrop: 'पीक',
    filterLocation: 'ठिकाण',
    filterGrade: 'गुणवत्ता दर्जा',
    minPrice: 'किमान किंमत',
    maxPrice: 'कमाल किंमत',
    qualityFilter: 'गुणवत्ता',
    allQuality: 'सर्व गुणवत्ता स्तर',
    gradeA: 'श्रेणी A',
    gradeB: 'श्रेणी B',
    gradeC: 'श्रेणी C',
    applyFilters: 'फिल्टर लागू करा',
    clearFilters: 'फिल्टर साफ करा',
    sortBy: 'क्रमवारी',
    highestPrice: 'सर्वाधिक किंमत',
    lowestPrice: 'सर्वात कमी किंमत',
    nearestMarket: 'सर्वात जवळचा बाजार',
    bestNetReturnSort: 'सर्वोत्तम निव्वळ परतावा',

    // QUALITY
    quality: 'गुणवत्ता',
    qualityGrade: 'गुणवत्ता श्रेणी',
    addQuality: 'गुणवत्ता जोडा',
    selectQuality: 'गुणवत्ता श्रेणी निवडा',
    farmerDeclaredQuality: 'शेतकऱ्याने सांगितलेली गुणवत्ता',
    buyerVerifiedQuality: 'खरेदीदाराने तपासलेली गुणवत्ता',
    qualityInspection: 'गुणवत्ता तपासणी',
    qualityDescription: 'गुणवत्तेचे वर्णन',
    qualityNotes: 'गुणवत्ता नोंदी',
    gradeThisProduce: 'या मालाचे श्रेणीकरण करा',
    gradingTag: 'गुणवत्ता श्रेणीकरण',
    assignGrade: 'गुणवत्ता श्रेणी नियुक्त करा',
    gradeALabel: 'श्रेणी A · प्रीमियम',
    gradeANote: 'किमान दोष, एकसमान आकार/रंग.',
    gradeBLabel: 'श्रेणी B · मानक',
    gradeBNote: 'किरकोळ दोष, बाजारात स्वीकार्य.',
    gradeCLabel: 'श्रेणी C · मानकाखाली',
    gradeCNote: 'स्पष्ट दोष किंवा नुकसान.',
    finalPriceLabel: 'श्रेणीकरणानंतरची अंतिम किंमत (₹/क्विंटल)',
    totalAtPricePrefix: 'या किंमतीत एकूण:',
    finalizeGradingBtn: 'श्रेणीकरण व किंमत निश्चित करा',
    gradeSetPriceBtn: 'श्रेणीकरण करा व अंतिम किंमत ठरवा',
    gradedByBuyerNote:
      'खरेदीदाराने श्रेणीकरण व किंमत निश्चित केली. पुढील पायरी: स्वीकारलेल्या प्रमाणासाठी वाहतूक आयोजित करा.',
    offerAcceptedGradeNote:
      'प्रोटोटाइपमध्ये खरेदीदार संपर्क स्थापित. पुढील पायरी: खरेदीदार गुणवत्तेचे श्रेणीकरण करून अंतिम किंमत ठरवेल.',
    planTransportBtn: 'या ऑफरसाठी वाहतूक आयोजित करा',

    // RATING
    rating: 'रेटिंग',
    ratings: 'रेटिंग्स',
    farmerRating: 'शेतकरी रेटिंग',
    rateFarmer: 'या शेतकऱ्याला रेट करा',
    rateYourExperience: 'तुमचा अनुभव रेट करा',
    starRating: 'स्टार रेटिंग',
    review: 'अभिप्राय',
    writeReview: 'अभिप्राय लिहा',
    submitRating: 'रेटिंग सबमिट करा',
    ratingSubmitted: 'रेटिंग यशस्वीरित्या सबमिट झाली.',
    ratingEligibility:
      'शेतकऱ्याकडून खरेदी पूर्ण केल्यानंतरच तुम्ही त्याला रेट करू शकता.',
    notEligibleToRate: 'तुम्हाला सध्या या शेतकऱ्याला रेट करण्याची परवानगी नाही.',
    completedTransactionRequired:
      'रेटिंग देण्यासाठी व्यवहार पूर्ण झालेला असणे आवश्यक आहे.',

    // LOGISTICS
    logistics: 'वाहतूक',
    logisticsTag: 'वाहतूक',
    moveProduce: 'तुमचा माल हलवा',
    transport: 'वाहतूक',
    transportOptionsTag: 'वाहतूक पर्याय',
    chooseTransport: 'वाहतुकीचा पर्याय निवडा',
    transportVehicle: 'वाहन',
    truck: 'ट्रक',
    miniTruck: 'मिनी ट्रक',
    pickupTruck: 'पिकअप ट्रक',
    estimatedCost: 'अंदाजित खर्च',
    distance: 'अंतर',
    pickup: 'पिकअप',
    delivery: 'डिलिव्हरी',
    pickupAddress: 'पिकअप ठिकाण',
    deliveryAddress: 'डिलिव्हरी ठिकाण',
    schedulePickupTitle: 'पिकअप वेळ ठरवा',
    pickupDateLabel: 'पिकअप तारीख',
    pickupTimeLabel: 'पिकअप वेळ',
    schedulePickupBtn: 'पिकअप ठरवा',
    confirmTransport: 'वाहतूक निश्चित करा',
    transportScheduled: 'वाहतूक यशस्वीरित्या निश्चित झाली.',
    transportEstimate: 'वाहतूक अंदाज',
    transportAvailable: 'वाहतूक उपलब्ध',
    noTransportAvailable: 'वाहतुकीचा पर्याय उपलब्ध नाही.',
    transportRate: 'वाहतूक दर',
    costPerKm: 'प्रति किमी खर्च',

    // FRUITS
    fruits: 'फळे',
    vegetables: 'भाज्या',
    grains: 'धान्य',
    pulses: 'डाळी',
    spices: 'मसाले',
    selectCategory: 'श्रेणी निवडा',
    mango: 'आंबा',
    banana: 'केळी',
    apple: 'सफरचंद',
    orange: 'संत्रे',
    grapes: 'द्राक्षे',
    pomegranate: 'डाळिंब',
    guava: 'पेरू',
    papaya: 'पपई',
    watermelon: 'टरबूज',
    onion: 'कांदा',
    potato: 'बटाटा',
    tomato: 'टोमॅटो',
    cabbage: 'कोबी',
    cauliflower: 'फुलकोबी',
    brinjal: 'वांगी',

    // MSP
    msp: 'MSP',
    mspFull: 'किमान आधारभूत किंमत',
    mspBenchmarkTitle: 'सरकारी MSP तुलना',
    marketVsMsp: 'बाजारभाव विरुद्ध MSP',
    mspDifference: 'MSP मधील फरक',
    marketAboveMsp: 'बाजारभाव MSP पेक्षा जास्त आहे.',
    marketBelowMsp: 'बाजारभाव MSP पेक्षा कमी आहे.',
    mspNotAvailable: 'या पिकासाठी MSP डेटा उपलब्ध नाही.',
    mspSource: 'MSP स्रोत',
    mspYear: 'MSP वर्ष',
    mspSeason: 'विपणन हंगाम',
    checkProcurementOptions:
      'विक्री करण्यापूर्वी उपलब्ध सरकारी खरेदी पर्याय तपासा.',

    // DECISION
    recommendation: 'शिफारस',
    recommendationTag: 'कृषीसेतू शिफारस',
    sellingRecommendation: 'विक्रीची शिफारस',
    recommendedAction: 'शिफारस केलेली कृती',
    highestReturn: 'सर्वाधिक परतावा',
    betterOption: 'चांगला पर्याय',
    decisionEngine: 'निर्णय इंजिन',
    netRealization: 'निव्वळ प्राप्ती',
    netRealizationEngine: 'निव्वळ प्राप्ती इंजिन',
    grossValue: 'एकूण मूल्य',
    totalCosts: 'एकूण खर्च',
    spoilageRisk: 'नासाडीचा धोका',
    lowSpoilageRisk: 'कमी नासाडीचा धोका',
    mediumSpoilageRisk: 'मध्यम नासाडीचा धोका',
    highSpoilageRisk: 'जास्त नासाडीचा धोका',
    demandScore: 'मागणी गुण',
    priceTrendScore: 'किंमत कल गुण',
    transportScore: 'वाहतूक गुण',

    // OFFLINE
    offline: 'ऑफलाइन',
    online: 'ऑनलाइन',
    cached: 'कॅश केलेला डेटा',
    offlineMode: 'ऑफलाइन मोड',
    offlineAvailable: 'ऑफलाइन उपलब्ध',
    lastUpdated: 'शेवटचे अपडेट',
    syncData: 'डेटा सिंक करा',
    syncing: 'सिंक होत आहे...',
    syncComplete: 'डेटा यशस्वीरित्या सिंक झाला.',

    // HEADER
    startDemo: 'SIH डेमो सुरू करा',
    backToComparison: '← तुलनेकडे परत जा',
    accessKrishiSetu: 'कृषीसेतू वापरा',
    krishiSetu: 'कृषीसेतू',

    // IMPACT
    impactBannerTag: 'अंदाजित परिणाम (नमुना गट)',
    impactBannerBadge: 'डेमो आकडे — अजून मोजलेले नाही',
    impactFarmersHelped: 'मदत झालेले शेतकरी (डेमो गट)',
    impactReturnLift: 'जवळच्या बाजारापेक्षा सरासरी परतावा वाढ',
    impactMarketsCompared: 'प्रत्येक निर्णयासाठी तुलना केलेले बाजार',

    // TRANSACTION
    transaction: 'व्यवहार',
    transactionDetails: 'व्यवहाराची माहिती',
    acceptedQuantity: 'स्वीकारलेले प्रमाण',
    finalPrice: 'अंतिम किंमत',
    totalAmount: 'एकूण रक्कम',
    transactionCompleted: 'व्यवहार पूर्ण झाला.',
    transactionPending: 'व्यवहार प्रलंबित आहे.',
    purchaseCompleted: 'खरेदी पूर्ण झाली.',
    purchaseHistory: 'खरेदी इतिहास',

    // ERRORS
    somethingWentWrong: 'काहीतरी चूक झाली.',
    pleaseTryAgain: 'कृपया पुन्हा प्रयत्न करा.',
    requiredField: 'हे फील्ड आवश्यक आहे.',
    enterValidQuantity: 'कृपया योग्य प्रमाण भरा.',
    enterValidPrice: 'कृपया योग्य किंमत भरा.',
    selectCropError: 'कृपया पीक निवडा.',
    selectLocationError: 'कृपया ठिकाण निवडा.',
    selectQualityError: 'कृपया गुणवत्ता श्रेणी निवडा.',
    loginRequired: 'पुढे जाण्यासाठी कृपया लॉगिन करा.',
    buyerOnly: 'ही कृती फक्त खरेदीदारांसाठी उपलब्ध आहे.',
    farmerOnly: 'ही कृती फक्त शेतकऱ्यांसाठी उपलब्ध आहे.',
    transactionRequired: 'व्यवहार पूर्ण झालेला असणे आवश्यक आहे.',
    apiError: 'लाइव्ह बाजारभाव मिळवता आला नाही.',
    noMarketData: 'बाजाराचा डेटा उपलब्ध नाही.',
    noForecastData: 'अंदाजाचा डेटा उपलब्ध नाही.',

    // FOOTER
    aboutKrishiSetu: 'कृषीसेतूबद्दल',
    howItWorks: 'हे कसे काम करते',
    privacy: 'गोपनीयता',
    terms: 'अटी',
    help: 'मदत',
    support: 'सपोर्ट',
    prototype: 'प्रोटोटाइप',
    demo: 'डेमो',
    sample: 'नमुना',
    allValuesEstimate:
      'दाखवलेली सर्व मूल्ये प्रोटोटाइप प्रात्यक्षिकासाठी अंदाजित आहेत.',

    // COMMON PHRASES
    marketSuffix: 'बाजार',
    pricePerQuintal: '₹/क्विंटल',
    perQuintal: 'प्रति क्विंटल',
    quintals: 'क्विंटल',
    kg: 'किलो',
    tonnes: 'टन',
    km: 'किमी',
    rupees: '₹',

    // DYNAMIC
    todayCropPrice: '{crop} चा आजचा बाजारभाव',
    bestReturnForCrop: '{crop} साठी सर्वोत्तम अंदाजित परतावा',
    whereToSellCrop: '{crop} कुठे विकावा?',
    marketDistanceText: '{distance} किमी अंतर',
    availableQuantityText: '{quantity} क्विंटल उपलब्ध',
    offerPriceText: '₹{price}/क्विंटल',
    totalAmountText: '₹{amount}',
    ratingText: '{rating}/5',
  },

  'हिंदी': {
    // =========================
    // COMMON
    // =========================
    dashboard: 'डैशबोर्ड',
    home: 'होम',
    back: 'वापस',
    next: 'आगे',
    previous: 'पिछला',
    continue: 'जारी रखें',
    submit: 'सबमिट करें',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
    yes: 'हाँ',
    no: 'नहीं',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    reset: 'रीसेट',
    refresh: 'रिफ्रेश',
    loading: 'लोड हो रहा है...',
    retry: 'फिर कोशिश करें',
    viewDetails: 'विवरण देखें →',
    optional: 'वैकल्पिक',
    required: 'अनिवार्य',
    available: 'उपलब्ध',
    total: 'कुल',
    status: 'स्थिति',
    date: 'तारीख',
    time: 'समय',
    name: 'नाम',
    phone: 'फोन नंबर',
    email: 'ईमेल',
    language: 'भाषा',
    price: 'कीमत',
    quantity: 'मात्रा',
    location: 'स्थान',
    crop: 'फसल',
    farmer: 'किसान',
    buyer: 'खरीदार',
    company: 'कंपनी',
    market: 'बाज़ार',
    markets: 'बाज़ार',
    offer: 'ऑफ़र',
    offers: 'खरीदार ऑफ़र',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    pending: 'लंबित',
    completed: 'पूर्ण',

    // ROLE
    chooseRole: 'अपनी भूमिका चुनें',
    selectRole: 'आप KrishiSetu का उपयोग कैसे करना चाहते हैं, चुनें',
    iAmFarmer: 'मैं किसान हूँ',
    iAmBuyer: 'मैं खरीदार हूँ',
    farmerDescription: 'अपनी उपज के लिए बेहतर से बेहतर शुद्ध रिटर्न प्राप्त करें।',
    buyerDescription: 'गुणवत्तापूर्ण उपज खोजें और किसानों से सीधे जुड़ें।',
    farmerRole: 'किसान',
    buyerRole: 'खरीदार',

    // LOGIN
    login: 'लॉगिन',
    register: 'रजिस्टर करें',
    farmerLogin: 'किसान लॉगिन',
    buyerLogin: 'खरीदार लॉगिन',
    farmerRegistration: 'किसान पंजीकरण',
    buyerRegistration: 'खरीदार पंजीकरण',
    enterDetails: 'जारी रखने के लिए अपनी जानकारी भरें।',
    enterFarmerDetails: 'किसान के रूप में जारी रखने के लिए अपनी जानकारी भरें।',
    enterBuyerDetails: 'खरीदार के रूप में जारी रखने के लिए अपनी जानकारी भरें।',
    farmerName: 'किसान का नाम',
    businessName: 'व्यवसाय / संस्था का नाम',
    companyName: 'कंपनी का नाम',
    mobileNumber: 'मोबाइल नंबर',
    enterMobileNumber: 'मोबाइल नंबर दर्ज करें',
    sendOtp: 'OTP भेजें',
    verifyOtp: 'OTP सत्यापित करें',
    enterOtp: 'OTP दर्ज करें',
    otpSent: 'OTP सफलतापूर्वक भेज दिया गया है।',
    invalidOtp: 'अमान्य OTP। फिर कोशिश करें।',
    loginSuccessful: 'लॉगिन सफल हुआ।',
    registrationSuccessful: 'पंजीकरण सफल हुआ।',
    uploadId: 'डिजिटल किसान पहचान पत्र अपलोड करें',
    digitalFarmerId: 'डिजिटल किसान पहचान पत्र (किसान पहचान पत्र)',
    chooseFile: 'फाइल चुनें',
    noFileChosen: 'कोई फाइल नहीं चुनी गई',
    idUploadOptional: 'डिजिटल किसान पहचान पत्र अपलोड करना वैकल्पिक है।',
    qualityCertificate: 'गुणवत्ता प्रमाणपत्र',
    qualityCertificateOptional: 'गुणवत्ता प्रमाणपत्र वैकल्पिक है।',
    profileCreated: 'प्रोफाइल सफलतापूर्वक बनाई गई।',

    // FARMER
    farmerDashboard: 'किसान डैशबोर्ड',
    farmerDashboardSubtitle: 'अपनी उपज के लिए सबसे अच्छा बाज़ार खोजें।',
    whatsYourName: 'आपका नाम क्या है?',
    enterYourName: 'अपना नाम दर्ज करें',
    welcomeFarmer: 'स्वागत है, किसान',
    yourProduce: 'आपकी उपज',
    addProduce: 'उपज जोड़ें',
    addProduceListing: 'उपज की लिस्टिंग बनाएं',
    cropDetails: 'फसल की जानकारी',
    selectCrop: 'फसल चुनें',
    enterQuantity: 'मात्रा दर्ज करें',
    quantityUnit: 'मात्रा (क्विंटल)',
    expectedPrice: 'अपेक्षित कीमत',
    expectedPricePerQuintal: 'अपेक्षित कीमत (₹/क्विंटल)',
    selectLocation: 'स्थान चुनें',
    useMyLocation: 'मेरा स्थान इस्तेमाल करें',
    findBestMarket: 'सबसे अच्छा बाज़ार खोजें',
    compareMarkets: 'बाज़ारों की तुलना करें',
    whereShouldYouSell: 'आपको अपनी उपज कहाँ बेचनी चाहिए?',
    bestMarket: 'सबसे अच्छा बाज़ार',
    recommendedMarket: 'अनुशंसित बाज़ार',
    bestEstimatedReturn: 'सर्वश्रेष्ठ अनुमानित रिटर्न',
    todaysPrice: 'आज का भाव',
    currentPrice: 'वर्तमान कीमत',
    marketPrice: 'बाज़ार कीमत',
    governmentMsp: 'सरकारी MSP',
    mspBenchmark: 'MSP बेंचमार्क',
    aboveMsp: 'MSP से अधिक',
    belowMsp: 'MSP से कम',
    mspNotApplicable: 'MSP लागू नहीं है',
    priceDifference: 'MSP से अंतर',
    netReturn: 'शुद्ध रिटर्न',
    estimatedNetReturn: 'अनुमानित शुद्ध रिटर्न',
    expectedNetReturn: 'अपेक्षित शुद्ध रिटर्न',
    estimatedTransport: 'अनुमानित परिवहन',
    transportCost: 'परिवहन लागत',
    handlingCost: 'हैंडलिंग लागत',
    otherCosts: 'अन्य लागत',
    grossRevenue: 'कुल आय',
    decision: 'निर्णय',
    sellingDecision: 'बिक्री का निर्णय',
    sellNow: 'अभी बेचें',
    wait: 'प्रतीक्षा करें',
    sellAt: 'यहाँ बेचें',
    highestReturnNote: 'परिवहन लागत के बाद सबसे अधिक अनुमानित शुद्ध रिटर्न।',
    whyLabel: 'क्यों?',
    demoEstimate: 'डेमो अनुमान',
    sampleData: 'नमूना डेटा',
    sampleDataFooter:
      'नमूना / ऐतिहासिक डेटा · सभी मान प्रोटोटाइप प्रदर्शन हेतु अनुमानित हैं।',

    // COMPARISON
    comparisonTag: 'बाज़ार तुलना',
    comparisonTitlePrefix: 'आप अपनी उपज कहाँ बेचें',
    comparisonSubtitlePrefix:
      'सर्वाधिक अनुमानित शुद्ध रिटर्न के अनुसार क्रमबद्ध',
    comparisonSubtitleSuffix: 'क्विंटल के लिए।',
    backToDashboard: '← डैशबोर्ड पर वापस जाएं',
    bestNetReturn: 'सर्वश्रेष्ठ शुद्ध रिटर्न',
    kmAway: 'किमी दूर',
    demandSuffix: 'मांग',
    priceLabel: 'कीमत',
    transportLabel: 'परिवहन',
    handlingLabel: 'हैंडलिंग',
    netReturnLabel: 'शुद्ध रिटर्न',
    marketComparison: 'बाज़ार तुलना',
    compareMarketPrices: 'बाज़ार कीमतों की तुलना करें',
    estimatedRevenue: 'अनुमानित आय',
    estimatedProfit: 'अनुमानित लाभ',
    marketDistance: 'बाज़ार की दूरी',
    demand: 'मांग',
    highDemand: 'उच्च मांग',
    mediumDemand: 'मध्यम मांग',
    lowDemand: 'कम मांग',

    // FORECAST
    forecast: 'पूर्वानुमान',
    priceForecast: 'कीमत पूर्वानुमान',
    marketForecastEngine: 'बाज़ार पूर्वानुमान और निर्णय इंजन',
    marketForecastAndDesignEngine: 'बाज़ार पूर्वानुमान और निर्णय इंजन',
    priceTrends: 'कीमत रुझान',
    trends: 'कीमत रुझान',
    historicalPrices: 'ऐतिहासिक कीमतें',
    expectedPriceLabel: 'अपेक्षित कीमत',
    predictedPrice: 'अनुमानित कीमत',
    forecastPeriod: 'पूर्वानुमान अवधि',
    nextDays: 'अगले कुछ दिन',
    priceMovement: 'कीमत में बदलाव',
    rising: 'बढ़ रही है',
    falling: 'घट रही है',
    stable: 'स्थिर',
    trend: 'रुझान',
    forecastDisclaimer:
      'पूर्वानुमान उपलब्ध बाज़ार डेटा के आधार पर अनुमानित हैं।',

    // MARKETPLACE
    marketplace: 'बाज़ार',
    buyerMarketplaceTag: 'खरीदार बाज़ार',
    buyerMarketplace: 'खरीदार बाज़ार',
    findBuyers: 'खरीदार खोजें',
    findBuyersSubtitle:
      'अपनी उपज को प्रतिस्पर्धी कीमत देने वाले खरीदारों से जोड़ें।',
    findMoreBuyers: 'और खरीदार खोजें',
    myOffers: 'मेरी ऑफ़र',
    farmerOffers: 'किसान की ऑफ़र',
    buyerOffers: 'खरीदार ऑफ़र',
    buyerOffersTitle: 'खरीदार ऑफ़र',
    buyerOffersSubtitle: 'हर विवरण देखें और अंतिम निर्णय लें।',
    farmerDecisionsTag: 'किसान निर्णय',
    currentContextTitle: 'आपका वर्तमान बिक्री संदर्भ',
    offerComparisonTitle: 'ऑफ़र तुलना',
    currentMandiPrice: 'वर्तमान मंडी भाव',
    availableQuantity: 'उपलब्ध मात्रा',
    offeredPrice: 'प्रस्तावित कीमत',
    offerPrice: 'ऑफ़र कीमत',
    makeOffer: 'ऑफ़र दें',
    makeAnOffer: 'ऑफ़र दें',
    submitOffer: 'ऑफ़र सबमिट करें',
    offerSubmitted: 'ऑफ़र सफलतापूर्वक सबमिट हुई।',
    offerSubmittedTitle: 'ऑफ़र सबमिट हुई',
    pendingFarmerResponse: 'किसान की प्रतिक्रिया की प्रतीक्षा में',
    offerAcceptedTitle: 'ऑफ़र स्वीकार हुई',
    offerRejected: 'ऑफ़र अस्वीकार हुई',
    offerRejectedMessage: 'यह ऑफ़र अस्वीकार कर दी गई।',
    offerMessage: 'संदेश',
    optionalMessage: 'संदेश (वैकल्पिक)',
    buyerCompany: 'खरीदार कंपनी',
    loggedInBuyer: 'लॉग-इन खरीदार',
    buyerIdentity: 'खरीदार पहचान',
    offerBelongsToCompany:
      'यह ऑफ़र आपकी पंजीकृत कंपनी की ओर से दी जाएगी।',
    noOffers: 'कोई ऑफ़र उपलब्ध नहीं है।',
    noListings: 'कोई लिस्टिंग नहीं मिली।',
    listing: 'लिस्टिंग',
    listings: 'लिस्टिंग',
    createListing: 'लिस्टिंग बनाएं',
    produceListing: 'उपज लिस्टिंग',
    farmerListing: 'किसान लिस्टिंग',
    seller: 'विक्रेता',
    buyerDetails: 'खरीदार की जानकारी',
    farmerDetails: 'किसान की जानकारी',

    // FILTERS
    filterCrop: 'फसल',
    filterLocation: 'स्थान',
    filterGrade: 'गुणवत्ता ग्रेड',
    minPrice: 'न्यूनतम कीमत',
    maxPrice: 'अधिकतम कीमत',
    qualityFilter: 'गुणवत्ता',
    allQuality: 'सभी गुणवत्ता स्तर',
    gradeA: 'ग्रेड A',
    gradeB: 'ग्रेड B',
    gradeC: 'ग्रेड C',
    applyFilters: 'फ़िल्टर लागू करें',
    clearFilters: 'फ़िल्टर साफ़ करें',
    sortBy: 'क्रमबद्ध करें',
    highestPrice: 'सबसे अधिक कीमत',
    lowestPrice: 'सबसे कम कीमत',
    nearestMarket: 'सबसे नज़दीकी बाज़ार',
    bestNetReturnSort: 'सर्वश्रेष्ठ शुद्ध रिटर्न',

    // QUALITY
    quality: 'गुणवत्ता',
    qualityGrade: 'गुणवत्ता ग्रेड',
    addQuality: 'गुणवत्ता जोड़ें',
    selectQuality: 'गुणवत्ता ग्रेड चुनें',
    farmerDeclaredQuality: 'किसान द्वारा बताई गई गुणवत्ता',
    buyerVerifiedQuality: 'खरीदार द्वारा सत्यापित गुणवत्ता',
    qualityInspection: 'गुणवत्ता जांच',
    qualityDescription: 'गुणवत्ता विवरण',
    qualityNotes: 'गुणवत्ता नोट्स',
    gradeThisProduce: 'इस उपज का ग्रेड निर्धारित करें',
    gradingTag: 'गुणवत्ता ग्रेडिंग',
    assignGrade: 'गुणवत्ता ग्रेड निर्धारित करें',
    gradeALabel: 'ग्रेड A · प्रीमियम',
    gradeANote: 'न्यूनतम दोष, समान आकार/रंग।',
    gradeBLabel: 'ग्रेड B · मानक',
    gradeBNote: 'मामूली दोष, बाज़ार में स्वीकार्य।',
    gradeCLabel: 'ग्रेड C · मानक से नीचे',
    gradeCNote: 'स्पष्ट दोष या नुकसान।',
    finalPriceLabel: 'ग्रेडिंग के बाद अंतिम कीमत (₹/क्विंटल)',
    totalAtPricePrefix: 'इस कीमत पर कुल:',
    finalizeGradingBtn: 'ग्रेडिंग और कीमत तय करें',
    gradeSetPriceBtn: 'ग्रेडिंग करें और अंतिम कीमत तय करें',
    gradedByBuyerNote:
      'खरीदार द्वारा ग्रेडिंग और कीमत तय की गई। अगला चरण: स्वीकृत मात्रा के लिए परिवहन की व्यवस्था करें।',
    offerAcceptedGradeNote:
      'प्रोटोटाइप में खरीदार संपर्क स्थापित। अगला चरण: खरीदार गुणवत्ता का ग्रेड निर्धारित कर अंतिम कीमत तय करेगा।',
    planTransportBtn: 'इस ऑफ़र के लिए परिवहन की योजना बनाएं',

    // RATING
    rating: 'रेटिंग',
    ratings: 'रेटिंग्स',
    farmerRating: 'किसान रेटिंग',
    rateFarmer: 'इस किसान को रेट करें',
    rateYourExperience: 'अपने अनुभव को रेट करें',
    starRating: 'स्टार रेटिंग',
    review: 'समीक्षा',
    writeReview: 'समीक्षा लिखें',
    submitRating: 'रेटिंग सबमिट करें',
    ratingSubmitted: 'रेटिंग सफलतापूर्वक सबमिट हुई।',
    ratingEligibility:
      'किसान से खरीद पूरी करने के बाद ही आप उसे रेट कर सकते हैं।',
    notEligibleToRate: 'आप अभी इस किसान को रेट नहीं कर सकते।',
    completedTransactionRequired:
      'रेटिंग देने के लिए लेनदेन पूरा होना आवश्यक है।',

    // LOGISTICS
    logistics: 'लॉजिस्टिक्स',
    logisticsTag: 'लॉजिस्टिक्स',
    moveProduce: 'अपनी उपज भेजें',
    transport: 'परिवहन',
    transportOptionsTag: 'परिवहन विकल्प',
    chooseTransport: 'परिवहन का तरीका चुनें',
    transportVehicle: 'परिवहन वाहन',
    truck: 'ट्रक',
    miniTruck: 'मिनी ट्रक',
    pickupTruck: 'पिकअप ट्रक',
    estimatedCost: 'अनुमानित लागत',
    distance: 'दूरी',
    pickup: 'पिकअप',
    delivery: 'डिलीवरी',
    pickupAddress: 'पिकअप स्थान',
    deliveryAddress: 'डिलीवरी स्थान',
    schedulePickupTitle: 'पिकअप शेड्यूल करें',
    pickupDateLabel: 'पिकअप तारीख',
    pickupTimeLabel: 'पिकअप समय',
    schedulePickupBtn: 'पिकअप शेड्यूल करें',
    confirmTransport: 'परिवहन की पुष्टि करें',
    transportScheduled: 'परिवहन सफलतापूर्वक निर्धारित हुआ।',
    transportEstimate: 'परिवहन अनुमान',
    transportAvailable: 'परिवहन उपलब्ध',
    noTransportAvailable: 'परिवहन विकल्प उपलब्ध नहीं है।',
    transportRate: 'परिवहन दर',
    costPerKm: 'प्रति किमी लागत',

    // FRUITS
    fruits: 'फल',
    vegetables: 'सब्ज़ियाँ',
    grains: 'अनाज',
    pulses: 'दालें',
    spices: 'मसाले',
    selectCategory: 'श्रेणी चुनें',
    mango: 'आम',
    banana: 'केला',
    apple: 'सेब',
    orange: 'संतरा',
    grapes: 'अंगूर',
    pomegranate: 'अनार',
    guava: 'अमरूद',
    papaya: 'पपीता',
    watermelon: 'तरबूज',
    onion: 'प्याज़',
    potato: 'आलू',
    tomato: 'टमाटर',
    cabbage: 'पत्तागोभी',
    cauliflower: 'फूलगोभी',
    brinjal: 'बैंगन',

    // MSP
    msp: 'MSP',
    mspFull: 'न्यूनतम समर्थन मूल्य',
    mspBenchmarkTitle: 'सरकारी MSP बेंचमार्क',
    marketVsMsp: 'बाज़ार कीमत बनाम MSP',
    mspDifference: 'MSP से अंतर',
    marketAboveMsp: 'बाज़ार कीमत MSP से अधिक है।',
    marketBelowMsp: 'बाज़ार कीमत MSP बेंचमार्क से कम है।',
    mspNotAvailable: 'इस फसल के लिए MSP डेटा उपलब्ध नहीं है।',
    mspSource: 'MSP स्रोत',
    mspYear: 'MSP वर्ष',
    mspSeason: 'विपणन सीज़न',
    checkProcurementOptions:
      'बेचने से पहले उपलब्ध सरकारी खरीद विकल्पों की जांच करें।',

    // DECISION
    recommendation: 'सिफारिश',
    recommendationTag: 'कृषीसेतु सिफारिश',
    sellingRecommendation: 'बिक्री की सिफारिश',
    recommendedAction: 'अनुशंसित कार्रवाई',
    highestReturn: 'सबसे अधिक रिटर्न',
    betterOption: 'बेहतर विकल्प',
    decisionEngine: 'निर्णय इंजन',
    netRealization: 'शुद्ध प्राप्ति',
    netRealizationEngine: 'शुद्ध प्राप्ति इंजन',
    grossValue: 'कुल मूल्य',
    totalCosts: 'कुल लागत',
    spoilageRisk: 'खराब होने का जोखिम',
    lowSpoilageRisk: 'कम खराब होने का जोखिम',
    mediumSpoilageRisk: 'मध्यम खराब होने का जोखिम',
    highSpoilageRisk: 'अधिक खराब होने का जोखिम',
    demandScore: 'मांग स्कोर',
    priceTrendScore: 'कीमत रुझान स्कोर',
    transportScore: 'परिवहन स्कोर',

    // OFFLINE
    offline: 'ऑफ़लाइन',
    online: 'ऑनलाइन',
    cached: 'कैश डेटा',
    offlineMode: 'ऑफ़लाइन मोड',
    offlineAvailable: 'ऑफ़लाइन उपलब्ध',
    lastUpdated: 'अंतिम अपडेट',
    syncData: 'डेटा सिंक करें',
    syncing: 'सिंक हो रहा है...',
    syncComplete: 'डेटा सफलतापूर्वक सिंक हुआ।',

    // HEADER
    startDemo: 'SIH डेमो शुरू करें',
    backToComparison: '← तुलना पर वापस जाएं',
    accessKrishiSetu: 'कृषीसेतु का उपयोग करें',
    krishiSetu: 'कृषीसेतु',

    // IMPACT
    impactBannerTag: 'अनुमानित प्रभाव (नमूना समूह)',
    impactBannerBadge: 'डेमो आंकड़े — अभी मापे नहीं गए',
    impactFarmersHelped: 'मदद पाए किसान (डेमो समूह)',
    impactReturnLift: 'निकटतम मंडी की तुलना में औसत रिटर्न वृद्धि',
    impactMarketsCompared: 'प्रति निर्णय तुलना किए गए बाज़ार',

    // TRANSACTION
    transaction: 'लेनदेन',
    transactionDetails: 'लेनदेन विवरण',
    acceptedQuantity: 'स्वीकृत मात्रा',
    finalPrice: 'अंतिम कीमत',
    totalAmount: 'कुल राशि',
    transactionCompleted: 'लेनदेन पूरा हुआ।',
    transactionPending: 'लेनदेन लंबित है।',
    purchaseCompleted: 'खरीद पूरी हुई।',
    purchaseHistory: 'खरीद इतिहास',

    // ERRORS
    somethingWentWrong: 'कुछ गलत हो गया।',
    pleaseTryAgain: 'कृपया फिर कोशिश करें।',
    requiredField: 'यह फ़ील्ड आवश्यक है।',
    enterValidQuantity: 'कृपया सही मात्रा दर्ज करें।',
    enterValidPrice: 'कृपया सही कीमत दर्ज करें।',
    selectCropError: 'कृपया फसल चुनें।',
    selectLocationError: 'कृपया स्थान चुनें।',
    selectQualityError: 'कृपया गुणवत्ता ग्रेड चुनें।',
    loginRequired: 'जारी रखने के लिए कृपया लॉगिन करें।',
    buyerOnly: 'यह कार्रवाई केवल खरीदारों के लिए उपलब्ध है।',
    farmerOnly: 'यह कार्रवाई केवल किसानों के लिए उपलब्ध है।',
    transactionRequired: 'लेनदेन पूरा होना आवश्यक है।',
    apiError: 'लाइव बाज़ार डेटा प्राप्त नहीं हो सका।',
    noMarketData: 'बाज़ार डेटा उपलब्ध नहीं है।',
    noForecastData: 'पूर्वानुमान डेटा उपलब्ध नहीं है।',

    // FOOTER
    aboutKrishiSetu: 'कृषीसेतु के बारे में',
    howItWorks: 'यह कैसे काम करता है',
    privacy: 'गोपनीयता',
    terms: 'नियम',
    help: 'मदद',
    support: 'सहायता',
    prototype: 'प्रोटोटाइप',
    demo: 'डेमो',
    sample: 'नमूना',
    allValuesEstimate:
      'दिखाए गए सभी मान प्रोटोटाइप प्रदर्शन के लिए अनुमानित हैं।',

    // COMMON PHRASES
    marketSuffix: 'बाज़ार',
    pricePerQuintal: '₹/क्विंटल',
    perQuintal: 'प्रति क्विंटल',
    quintals: 'क्विंटल',
    kg: 'किलो',
    tonnes: 'टन',
    km: 'किमी',
    rupees: '₹',

    // DYNAMIC
    todayCropPrice: '{crop} का आज का बाज़ार भाव',
    bestReturnForCrop: '{crop} के लिए सर्वश्रेष्ठ अनुमानित रिटर्न',
    whereToSellCrop: '{crop} कहाँ बेचें?',
    marketDistanceText: '{distance} किमी दूर',
    availableQuantityText: '{quantity} क्विंटल उपलब्ध',
    offerPriceText: '₹{price}/क्विंटल',
    totalAmountText: '₹{amount}',
    ratingText: '{rating}/5',
  },
} as const

export type Labels = {
  [K in keyof typeof labels.English]: string
}

type LanguageContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  t: Labels
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({
  children,
}: {
  children: ReactNode
}) {
  const [language, setLanguage] = useState<Language>('English')

  const value: LanguageContextValue = {
    language,
    setLanguage,
    t: labels[language],
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext)

  if (!ctx) {
    throw new Error(
      'useLanguage must be used inside <LanguageProvider>',
    )
  }

  return ctx
}